generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: www.cfo.gov
  https: false
- host: www.paymentaccuracy.gov
  https: true
  tls_version: TLSv1.3
  cert_expires: Aug 22 21:53:05 2026 GMT
  hsts: true
  hsts_max_age: 31536000
- host: api.usaspending.gov
  https: true
  tls_version: TLSv1.2
  cert_expires: Oct 25 23:59:59 2026 GMT
  hsts: true
  hsts_max_age: 31536000
domains:
- domain: cfo.gov
  dnssec: true
  caa: []
  spf: true
  dmarc: true
  dmarc_policy: reject
- domain: paymentaccuracy.gov
  dnssec: true
  caa:
  - 0 issue "letsencrypt.org; accounturi=https://acme-v02.api.letsencrypt.org/acme/acct/73686273"
  - 0 issuewild ";"
  - 0 issue "letsencrypt.org; accounturi=https://acme-v02.api.letsencrypt.org/acme/acct/73686272"
  - 0 iodef "mailto:DL.OMB.MAXExtCerts@omb.eop.gov"
  spf: true
  dmarc: true
  dmarc_policy: reject
